#spring.thymeleaf.cache=false
#server.port=8081
#spring.datasource.generate-unique-name=false
#spring.datasource.name=tacocloud
#spring.datasource.url=jdbc:h2:D:/workspace_idea/tacocloudh2db/tacocloud;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=123456
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.trace=false
#spring.h2.console.settings.web-allow-others=true
#logging.level.sql=debug
spring:
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: tacocloud
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tacocloud;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8081
logging:
  level:
    sql: debug
